### ISSUE TITLE
Doesn't run well on Python 3.9, Pygame 2

### ISSUE THREAD

**Issue by limburgher** [pygame/solarwolf#8]
I'm the Fedora solarwolf package maintainer. We're currently shipping a snapshot, d19d830. It's missing some fixes present in master, but I noticed that on Fedora 33, the packaged version doesn't display right with Python 3.9, and when I upgrade to pygame2, it doesn't run at all. master behaves the same way, and I have yet to find any other code impacted at all by upgrading to pygame 2.

**Comment by ankith26** [comment]
Hmm that’s weird.
pygame 2 brings support for python 3.8 and 3.9, so I am not surprised if solarwolf does not work with pygame 1 and Python 3.9. But pygame 2 not working is an issue, so could you elaborate on the issue, on where it’s caused, any error message, and maybe file an issue on the pygame repo
Thanks!

**Comment by limburgher** [comment]
![image](https://user-images.githubusercontent.com/2363820/103553509-27bf8300-4e73-11eb-858e-722f5b1be734.png)
This is the error I get with pygame 2.0.0 (SDL 2.0.12, python 3.9.1)

**Comment by ankith26** [comment]
Are you sure you are on the main branch? Because that was fixed in PR #6

**Comment by limburgher** [comment]
It looks like I wasn't. I am now, and it opens the window, and just hangs, does nothing.

**Comment by illume** [comment]
This is fixed.
